name: pycodestyle linting

on:
  
  push:
    
    paths:
      - '**.py'

    ignore-paths:
      - 'setup.py'
      - 'conf.py'

  pull_request:
    
    paths:
      - '**.py'

    ignore-paths:
      - 'setup.py'
      - 'conf.py'

jobs:

  lint:
    
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      
    - name: Set up python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'
    
    - name: Running linter
      run: |
        python -m pip install --upgrade pip
        pip install pylama
    
    - name: Linting
      run: |
        pylama -i E501 --skip conf.py,setup.py
