name: publish release

on:
  release:
    types: [ published ] 
    
jobs:
  
  build-and-upload:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
          
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        
    - name: modify setup.py version
      run: |
        sed -i -E '/version/s/version="\S*?"/version="${{ github.event.release.tag_name }}"/g' setup.py
        
    - name: build
      run: |
        python setup.py sdist bdist_wheel
        
    - name: publish to test-pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_PASSWD  }}
        repository_url: https://test.pypi.org/legacy/
        
    - name: publish to pypi
      if: "!github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_PASSWD  }}
