name: push

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

    steps:
      - uses: actions/checkout@v2
        
      - name: Run Fossa and upload data
        if: env.FOSSA_API_KEY != ''
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ env.FOSSA_API_KEY }}
    
      - name: Install dependencies
        run: |
          pip install pipreqs

      - name: Run pipreqs
        run: pipreqs --force

      - name: Commit changes if needed
        run: |
          git diff --quiet
          if [ $? -ne 0 ]; then
            git add .
            git commit -m "[chore] Update requirements"
            git push origin master
          fi
