name: push

on:
  push:

jobs:
  push:
    if: secrets.FOSSA_API_KEY != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run Fossa and upload data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
  
