name: setup

on:
  workflow_dispatch

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup setup.py
      run: |
        sed -i -E 's|name=\".*?\"|name="${"${{ github.event.repository.name }}"//-/_}"|g' setup.py
        sed -i -E 's|author=\".*?\"|author="${{ github.event.repository.owner.login }}"|g' setup.py
        sed -i -E 's|description=\".*?\"|description="${{ github.event.repository.description }}"|g' setup.py
        sed -i -E 's|url=\".*?\"|url="${{ github.event.repository.html_url }}"|g' setup.py

    - name: Setup conf.py
      run: |
        sed -i -E 's|project = ".*?"|project = "${"${{ github.event.repository.name }}"//-/_}"|g' docs/conf.py
        sed -i -E 's|copyright = ".*?"|copyright = "${{ github.event.repository.license.name }}"|g' docs/conf.py
        sed -i -E 's|author = ".*?"|author = "${{ github.event.repository.owner.login }}"|g' docs/conf.py

    - name: Rename package folder
      run: |
        mv python_package_automation/ ${"${{ github.event.repository.name }}"//-/_}/

    - name: Delete setup workflow
      run: |
        rm -f .github/workflows/setup.yml

    - name: Push changes to github
      run: |
        git add -A
        git config --global user.email "none@none.com"
        git config --global user.name "setup bot"
        git commit -m 'Setting up repo'
        git push origin ${{ github.ref }}
